@TodoApiMinimal_HostAddress = https://localhost:7032

POST {{TodoApiMinimal_HostAddress}}/todoitems
Content-Type: application/json

{
    "name":"walk dog",
    "isComplete":true
}

###
GET {{TodoApiMinimal_HostAddress}}/todoitems

###

GET {{TodoApiMinimal_HostAddress}}/todoitems/complete

###

@id=1
GET {{TodoApiMinimal_HostAddress}}/todoitems/{{id}}

###

GET {{TodoApiMinimal_HostAddress}}/todoitems/2

###
